default:
        image: maven:3-openjdk-11
stages:
        - prepare
        - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true  -Dmaven.repo.local=.m2/repository"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  key:
    files:
      - pom.xml
    prefix: "$CI_JOB_NAME"
  paths:
    - ./driver/.m2/repository



prepare:
  stage: prepare
  image: gitlab.desy.de:5555/dcache/self-signed-certs:latest
  variables:
    GITHUB_WORKSPACE: certs
  script:
    - mkdir ${GITHUB_WORKSPACE}
    - /entrypoint.sh hostcert.pem hostkey.pem ca-chain.pem

  artifacts:
    paths:
      - ${GITHUB_WORKSPACE}

test:
        stage: test
        script:
                - pwd
                - mkdir -p /etc/grid-security/
                - mv certs/hostcert.pem /etc/grid-security/.
                - mv certs/hostkey.pem /etc/grid-security/.
                - echo $CI_RUNNER_SHORT_TOKEN
                - echo "Now building with maven"
                - cd driver
                - mvn clean package
        artifacts:
                paths:
                        - driver/target/*.tar.gz
