default:
        image: maven:3-openjdk-11
stages:
        - prepare
        - test



prepare:
  stage: prepare
  image: gitlab.desy.de:5555/dcache/self-signed-certs:latest
  variables:
    GITHUB_WORKSPACE: /etc/grid-security
  script:
    - mkdir ${GITHUB_WORKSPACE}
    - ./entrypoint.sh hostcert.pem hostkey.pem ca-chain.pem

  artifacts:
    paths:
      - ${GITHUB_WORKSPACE}


test:
        stage: test
        script:
                - pwd
                - echo $CI_RUNNER_SHORT_TOKEN
                - echo "Now building with maven"
                - cd driver
                - mvn clean package
        artifacts:
                paths:
                        - driver/target/*.tar.gz
